base: /
disableStaticFileCache: false
errorHandling:
  -
    errorCode: 404
    errorHandler: Page
    errorContentSource: 't3://page?uid=3'
languages:
  -
    title: English
    enabled: true
    base: /
    typo3Language: default
    locale: en_US
    iso-639-1: en
    navigationTitle: English
    hreflang: en-US
    direction: ''
    flag: us
    languageId: 0
rootPageId: 1
routes:
  -
    route: robots.txt
    type: staticText
    content: "User-agent: *\r\nDisallow: /typo3/\r\nDisallow: /typo3_src/\r\nAllow: /typo3/sysext/frontend/Resources/Public/*\r\n"
  -
    route: sitemap.xml
    type: uri
    source: 'http://theme-testing.ddev.site/?sitemap=pages&type=1533906435'
websiteTitle: ''
