services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  NITSAN\NsThemeNewage\Updates\ContentBlockMigration:
    tags:
      - name: 'install.upgrade.wizard'

  NITSAN\NsThemeNewage\Service\ContentBlockMigration:
    public: true
